package com.path.payh.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class DGTL_MSG_DEFVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_MSG_DEF.DGTL_MSG_DEF_ID
     */
    private BigDecimal DGTL_MSG_DEF_ID;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.BRIEF_NAME
     */
    private String BRIEF_NAME;
    
    /**
     * This field corresponds to the database column DGTL_MSG_DEF.LONG_NAME
     */
    private String LONG_NAME;
    
    /**
     * This field corresponds to the database column DGTL_MSG_DEF.MSG_IDENTIFIER
     */
    private String MSG_IDENTIFIER;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.LOAD_FROM
     */
    private String LOAD_FROM;
    /**
     * This field corresponds to the database column DGTL_MSG_DEF.MSG_TYPE
     */
    private String MSG_TYPE;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column DGTL_MSG_DEF.MSG_SCHEMA
     */
    private String MSG_SCHEMA;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.DGTL_MSG_DEF_ID
     *
     * @return the value of DGTL_MSG_DEF.DGTL_MSG_DEF_ID
     */
    public BigDecimal getDGTL_MSG_DEF_ID() {
        return DGTL_MSG_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.DGTL_MSG_DEF_ID
     *
     * @param DGTL_MSG_DEF_ID the value for DGTL_MSG_DEF.DGTL_MSG_DEF_ID
     */
    public void setDGTL_MSG_DEF_ID(BigDecimal DGTL_MSG_DEF_ID) {
        this.DGTL_MSG_DEF_ID = DGTL_MSG_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.BRIEF_NAME
     *
     * @return the value of DGTL_MSG_DEF.BRIEF_NAME
     */
    public String getBRIEF_NAME() {
        return BRIEF_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.BRIEF_NAME
     *
     * @param CODE the value for DGTL_MSG_DEF.BRIEF_NAME
     */
    public void setBRIEF_NAME(String BRIEF_NAME) {
        this.BRIEF_NAME = BRIEF_NAME == null ? null : BRIEF_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.MSG_IDENTIFIER
     *
     * @return the value of DGTL_MSG_DEF.MSG_IDENTIFIER
     */
    public String getMSG_IDENTIFIER() {
        return MSG_IDENTIFIER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.MSG_IDENTIFIER
     *
     * @param DESCRIPTION the value for DGTL_MSG_DEF.MSG_IDENTIFIER
     */
    public void setMSG_IDENTIFIER(String MSG_IDENTIFIER) {
        this.MSG_IDENTIFIER = MSG_IDENTIFIER == null ? null : MSG_IDENTIFIER.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.LOAD_FROM
     *
     * @return the value of DGTL_MSG_DEF.LOAD_FROM
     */
    public String getLOAD_FROM() {
        return LOAD_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.LOAD_FROM
     *
     * @param DESCRIPTION the value for DGTL_MSG_DEF.LOAD_FROM
     */
    public void setLOAD_FROM(String LOAD_FROM) {
        this.LOAD_FROM = LOAD_FROM == null ? null : LOAD_FROM.trim();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.LONG_NAME
     *
     * @return the value of DGTL_MSG_DEF.LONG_NAME
     */
    public String getLONG_NAME() {
        return LONG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.LONG_NAME
     *
     * @param DESCRIPTION the value for DGTL_MSG_DEF.LONG_NAME
     */
    public void setLONG_NAME(String LONG_NAME) {
        this.LONG_NAME = LONG_NAME == null ? null : LONG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.MSG_TYPE
     *
     * @return the value of DGTL_MSG_DEF.MSG_TYPE
     */
    public String getMSG_TYPE() {
        return MSG_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.MSG_TYPE
     *
     * @param MSG_TYPE the value for DGTL_MSG_DEF.MSG_TYPE
     */
    public void setMSG_TYPE(String MSG_TYPE) {
        this.MSG_TYPE = MSG_TYPE == null ? null : MSG_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.CREATED_BY
     *
     * @return the value of DGTL_MSG_DEF.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.CREATED_BY
     *
     * @param CREATED_BY the value for DGTL_MSG_DEF.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.CREATED_DATE
     *
     * @return the value of DGTL_MSG_DEF.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.CREATED_DATE
     *
     * @param CREATED_DATE the value for DGTL_MSG_DEF.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.MODIFIED_BY
     *
     * @return the value of DGTL_MSG_DEF.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for DGTL_MSG_DEF.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.MODIFIED_DATE
     *
     * @return the value of DGTL_MSG_DEF.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for DGTL_MSG_DEF.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.APPROVED_BY
     *
     * @return the value of DGTL_MSG_DEF.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.APPROVED_BY
     *
     * @param APPROVED_BY the value for DGTL_MSG_DEF.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.APPROVED_DATE
     *
     * @return the value of DGTL_MSG_DEF.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for DGTL_MSG_DEF.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.DATE_UPDATED
     *
     * @return the value of DGTL_MSG_DEF.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for DGTL_MSG_DEF.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.DELETED_BY
     *
     * @return the value of DGTL_MSG_DEF.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.DELETED_BY
     *
     * @param DELETED_BY the value for DGTL_MSG_DEF.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.DELETED_DATE
     *
     * @return the value of DGTL_MSG_DEF.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.DELETED_DATE
     *
     * @param DELETED_DATE the value for DGTL_MSG_DEF.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.STATUS
     *
     * @return the value of DGTL_MSG_DEF.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.STATUS
     *
     * @param STATUS the value for DGTL_MSG_DEF.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_MSG_DEF.MSG_SCHEMA
     *
     * @return the value of DGTL_MSG_DEF.MSG_SCHEMA
     */
    public String getMSG_SCHEMA() {
        return MSG_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_MSG_DEF.MSG_SCHEMA
     *
     * @param MSG_SCHEMA the value for DGTL_MSG_DEF.MSG_SCHEMA
     */
    public void setMSG_SCHEMA(String MSG_SCHEMA) {
        this.MSG_SCHEMA = MSG_SCHEMA == null ? null : MSG_SCHEMA.trim();
    }
}